if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="individual_solutions-2";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import olympiad;
size(0, 200.5);
pair A = (0, 8);
pair B = (2, 10);
pair C = (4, 10);
pair D = (4, 2);
pair E = (6, 2);
pair F = (6, 0);
pair G = (0, 0);
pair H = (0, 2);
pair I = (2, 2);
pair J = (2, 6);
pair K = (0, 6);
path AB = A{right}..{up}B;
draw(AB);
label("$\pi$", midpoint(AB), NW);
draw(B--C--D--E--F--G--H--I--J--K--A);
label("2", midpoint(D--E), S);
label("2", (6,1), W);
label("6", midpoint(F--G), S);
label("4", midpoint(I--J), W);
label("2", midpoint(K--A), W);
label("$A$", A, NW);
label("$B$", B, NW);
label("$C$", C, NE);
label("$D$", D, NE);
label("$E$", E, NE);
label("$F$", F, SE);
label("$G$", G, SW);
label("$H$", H, NW);
label("$I$", I, NW);
label("$J$", J, SW);
label("$K$", K, SW);
